macro(find_package package)
  if(${package}_FOUND)
    return()
  endif()
  if(git.submodule.packages)
    list(FIND ${CMAKE_PROJECT_NAME}.submodules ${package} found_submodule)
    if(found_submodule GREATER "-1" AND ${package}.submodule)
      git_submodule_init(${package})
      git_submodule_update(${package})
      if(NOT EXISTS ${${package}.submodule.path}/CMakeLists.txt)
        message("")
        message("=======================")
        message("git submodule package, ${package}, does not contain a CMakeLists.txt file")
        message("The ${package} git submodule is located here: ${${package}.submodule.path}")
        message("${package} requested with find_package by ${CMAKE_PROJECT_NAME}")
        message("${CMAKE_PROJECT_NAME} is located here: ${PROJECT_SOURCE_DIR}")
        message("=======================")
        message("")
        message(FATAL_ERROR " find_package request failed")
      endif()
      add_subdirectory(${${package}.submodule.path})
      set(${package}_FOUND TRUE)
      return()
    endif()
  endif()

  previous_find_package(${ARGV})
endmacro()

wrap_find_package()
